name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the `main` branch
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-image:latest .
        docker tag ${{ secrets.DOCKER_USERNAME }}/my-image:latest ${{ secrets.DOCKER_USERNAME }}/my-image:23f1000799

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-image:23f1000799
